import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.0.3',
  date: '2023-01-05T12:08:21.710Z',
};
export default meta;
