import type MetaInterface from "@/interfaces/MetaInterface";

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: "1.0.3",
  date: "2023-01-30T09:40:52.310Z",
};
export default meta;
